version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: gunicorn oddstracker_admin.wsgi:application -c gunicorn.config.py --bind 0.0.0.0:8000 --enable-stdio-inheritance --capture-output --log-level debug
    volumes:
      - logging:/var/log/gunicorn/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev.db
  
volumes:
  postgres_data:
  static_volume:
  logging: