version: "3.4"
services:
  nginx-proxy:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: 013206471204.dkr.ecr.us-east-2.amazonaws.com/oddstracker-staging:nginx-proxy
    labels:
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: /Users/alexperez/Projects/odds/task-definition.json
    networks:
      ecs-local-network: null
    ports:
    - target: 443
      published: 443
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: certs
      target: /etc/nginx/certs
    - type: bind
      source: html
      target: /usr/share/nginx/html
    - type: bind
      source: vhost
      target: /etc/nginx/vhost.d
    - type: bind
      source: /var/run/docker.sock
      target: /tmp/docker.sock
  nginx-proxy-letsencrypt:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: jrcs/letsencrypt-nginx-proxy-companion
    labels:
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: /Users/alexperez/Projects/odds/task-definition.json
    links:
    - nginx-proxy
    networks:
      ecs-local-network: null
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: certs
      target: /etc/nginx/certs
    - type: bind
      source: html
      target: /usr/share/nginx/html
    - type: bind
      source: vhost
      target: /etc/nginx/vhost.d
  web:
    command:
    - gunicorn
    - oddstracker_admin.wsgi:application
    - --bind
    - 0.0.0.0:8000
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: 013206471204.dkr.ecr.us-east-2.amazonaws.com/oddstracker-staging:web
    labels:
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: /Users/alexperez/Projects/odds/task-definition.json
    networks:
      ecs-local-network: null
networks:
  ecs-local-network:
    external: true
