# Generated by Django 3.1.2 on 2020-10-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('game_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OddsSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('US', 'us'), ('UK', 'uk'), ('AU', 'au'), ('EU', 'eu')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddstracker.league')),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_recorded', models.DateTimeField()),
                ('mkt_type', models.CharField(choices=[('H2H', 'h2h'), ('SPREAD', 'spread'), ('TOTALS', 'totals')], max_length=100)),
                ('addl_value', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddstracker.game')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddstracker.oddssource')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddstracker.region'),
        ),
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddstracker.sport'),
        ),
    ]
