# Generated by Django 3.1.2 on 2020-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddstracker', '0002_auto_20201005_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='odds',
            name='team_a_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odds',
            name='team_b_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
